version: '3.8'

services:
  api:
    build: .
    ports:
      - '5100:5100'
    env_file:
      - .env.production
    depends_on:
      - mongo
    networks:
      - app-network

  mongo:
    image: mongo:6
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

volumes:
  mongo-data:

networks:
  app-network:
